apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  labels:
    app: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: 6
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
        - name: redis
          image: redis
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: client
            - containerPort: 16379
              name: gossip
          command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                   fieldPath: status.podIP       
          volumeMounts:
          - mountPath: /conf 
            name: conf
            readOnly: false
          - name: redis-volume-claim
            mountPath: /data
            readOnly: false
      volumes:
      - name: conf
        configMap: 
            name: redis-cluster
            defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: redis-volume-claim
    spec:
      storageClassName: default
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi