apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-cluster
  name: redis-cluster
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: client
    - port: 16379
      name: gossip
  selector:
    app: redis-cluster